---
abstract: "Like \"use lib <relative-path>\" but relative the file executing this command instead than the main program."
author:
  - 'Rocky Bernstein <rocky@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: relative_lib
provides:
  relative_lib:
    file: lib/relative_lib.pm
    version: 0.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
